language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

install:
  - git submodule update --init
  - cp ./config/config-dist.php ./config/config.php
  - cp controller/bootstap/config.default.php controller/config.php
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

before_script:
#  - composer global require "squizlabs/php_codesniffer=*"

script:
  - php -l agent.php
  - phpunit agent.php
  - php -l controller/controller.php
  - phpunit controller/controller.php
  - phpcs --standard=psr2 ./
